import streamlit as st
import json
from openai import OpenAI
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
import io

# --- 1. 設定 ---
api_key = st.secrets["OPENAI_API_KEY"]
client = OpenAI(api_key=api_key)

# テーマカラーの設定（ここで色を一括管理）
PRIMARY_COLOR = colors.HexColor("#E67E22") # 落ち着いたオレンジ
ACCENT_COLOR = colors.HexColor("#FDEBD0")  # 薄いクリーム色
TEXT_COLOR = colors.HexColor("#2C3E50")    # 濃いグレー

# --- 2. AI関数（プロンプトを強化） ---
def generate_recipe_json(ingredients, mode, condition, target, user_message):
    prompt = f"""
    あなたは「家庭料理のプロ」です。
    ユーザーは「{target}」へのプレゼントとしてレシピを作ります。
    以下の情報を元に、指定のJSON形式のみを出力してください。

    【ユーザー入力】
    * 食材: {ingredients}
    * 基本モード: {mode}
    * その他の条件: {condition}
    * 添えるメッセージ: {user_message}

    【重要ルール】
    1. 材料リストには、野菜・肉だけでなく「醤油」「砂糖」などの**調味料と、その分量も必ずすべて網羅すること**。
    2. 手順の中で「合わせ調味料を入れる」とする場合、その中身が何かも明確にすること。
    3. 親しみやすく、かつ読みやすい文章にすること。

    【出力フォーマット(JSON)】
    {{
      "title": "料理名（キャッチーに）",
      "cooking_time": "調理時間（例：15分）",
      "ingredients": [ 
        {{"name": "豚肉", "amount": "200g"}},
        {{"name": "醤油(A)", "amount": "大さじ1"}},
        {{"name": "みりん(A)", "amount": "大さじ1"}}
      ],
      "preparation": [ "下準備1", "下準備2" ],
      "steps": [ "工程1", "工程2" ],
      "chef_comment": "シェフからのワンポイントアドバイス"
    }}
    """

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}],
        response_format={"type": "json_object"}
    )
    return json.loads(response.choices[0].message.content)

# --- 3. PDF装飾用の関数（枠線などを描画） ---
def draw_page_frame(canvas, doc):
    canvas.saveState()
    # ページ全体の外枠
    canvas.setStrokeColor(PRIMARY_COLOR)
    canvas.setLineWidth(2)
    canvas.rect(10*mm, 10*mm, 190*mm, 277*mm) # A4サイズの内側に枠を描く
    
    # フッター
    canvas.setFont("Helvetica", 9)
    canvas.setFillColor(colors.grey)
    canvas.drawCentredString(A4[0]/2, 15*mm, "Generated by AI Recipe Gift")
    canvas.restoreState()

# --- 4. PDF生成関数（デザイン強化版） ---
def create_pdf_bytes(data, target_name, user_message_content):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4,
                            rightMargin=20*mm, leftMargin=20*mm,
                            topMargin=20*mm, bottomMargin=25*mm)
    
    # フォント設定
    font_path = "ipaexg.ttf" 
    try:
        pdfmetrics.registerFont(TTFont('JapaneseFont', font_path))
    except:
        st.error("エラー: ipaexg.ttf が見つかりません。")
        return None

    # スタイル定義
    styles = getSampleStyleSheet()
    
    # タイトルスタイル
    title_style = ParagraphStyle(
        name='TitleJp', fontName='JapaneseFont', fontSize=26, leading=32, 
        alignment=1, spaceAfter=10, textColor=PRIMARY_COLOR
    )
    # サブタイトル（For 〇〇）
    subtitle_style = ParagraphStyle(
        name='SubTitleJp', fontName='JapaneseFont', fontSize=14, leading=20, 
        alignment=1, spaceAfter=20, textColor=colors.grey
    )
    # 見出しスタイル
    heading_style = ParagraphStyle(
        name='HeadingJp', fontName='JapaneseFont', fontSize=16, leading=20, 
        spaceBefore=15, spaceAfter=10, textColor=TEXT_COLOR,
        borderPadding=5, borderWidth=0, backColor=None
    )
    # 本文スタイル
    body_style = ParagraphStyle(
        name='BodyJp', fontName='JapaneseFont', fontSize=11, leading=16, textColor=TEXT_COLOR
    )

    story = []

    # 1. タイトルセクション
    story.append(Paragraph(data['title'], title_style))
    story.append(Paragraph(f"For: {target_name}  |  ⏱ {data['cooking_time']}", subtitle_style))
    story.append(Spacer(1, 5*mm))

    # 2. メッセージカード（存在する場合のみ）
    if user_message_content:
        # テーブルを使って「カード風」の背景を作る
        msg_content = Paragraph(f"<b>Message:</b><br/>{user_message_content}", 
                                ParagraphStyle(name='MsgInside', fontName='JapaneseFont', fontSize=12, leading=18))
        msg_table = Table([[msg_content]], colWidths=[160*mm])
        msg_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), ACCENT_COLOR), # 背景色
            ('BOX', (0, 0), (-1, -1), 1, PRIMARY_COLOR),    # 枠線
            ('ROUNDEDCORNERS', [5, 5, 5, 5]),               # 角丸（ReportLabのバージョンによっては効かない場合あり）
            ('PADDING', (0, 0), (-1, -1), 15),              # 余白
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ]))
        story.append(msg_table)
        story.append(Spacer(1, 10*mm))

    # 3. 材料リスト（テーブルデザインで見やすく）
    story.append(Paragraph("🛒 材料 (Ingredients)", heading_style))
    
    ing_data = []
    # ヘッダー行はなしで、データのみを綺麗に並べる
    for item in data['ingredients']:
        ing_data.append([item['name'], item['amount']])
    
    t_ing = Table(ing_data, colWidths=[100*mm, 40*mm])
    t_ing.setStyle(TableStyle([
        ('FONT', (0, 0), (-1, -1), 'JapaneseFont', 11),
        ('TEXTCOLOR', (0, 0), (-1, -1), TEXT_COLOR),
        ('LINEBELOW', (0, 0), (-1, -1), 0.5, colors.lightgrey), # 下線
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('PADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(t_ing)
    story.append(Spacer(1, 8*mm))

    # 4. 作り方
    story.append(Paragraph("🍳 作り方 (Steps)", heading_style))
    
    # 下準備
    if data['preparation']:
        story.append(Paragraph("<b>【下準備】</b>", body_style))
        for prep in data['preparation']:
            story.append(Paragraph(f"・{prep}", body_style))
        story.append(Spacer(1, 3*mm))

    # 本工程（番号付き）
    for i, step in enumerate(data['steps'], 1):
        # 工程番号を目立たせる
        story.append(Paragraph(f"<b>Step {i}:</b> {step}", body_style))
        story.append(Spacer(1, 2*mm))

    # 5. シェフのコメント
    if 'chef_comment' in data:
        story.append(Spacer(1, 5*mm))
        story.append(Paragraph("👨‍🍳 Chef's Point", heading_style))
        story.append(Paragraph(data['chef_comment'], body_style))

    # ビルド（ページ装飾関数を適用）
    doc.build(story, onFirstPage=draw_page_frame, onLaterPages=draw_page_frame)
    buffer.seek(0)
    return buffer

# --- 5. Streamlit 画面構築 ---
def main():
    st.set_page_config(page_title="Recipe Gift", page_icon="🎁") # タブ表示の設定
    
    st.title("🎁 AI Recipe Gift Generator")
    st.markdown("大切な人へ、**世界に一つのレシピ**を贈りましょう。")

    with st.sidebar:
        st.header("📝 レシピの設定")
        ingredients = st.text_area("食材リスト", "豚肉、玉ねぎ、人参")
        target = st.text_input("贈る相手", "お母さん")
        mode = st.selectbox("モード", ["冷蔵庫のもので作る", "買い物して豪華に"])
        condition = st.text_input("好み・条件", "和食、ご飯が進む味、野菜多め")
        user_message = st.text_area("メッセージカードの内容", "いつも美味しいご飯をありがとう！たまにはゆっくり休んでね。")
        
        generate_btn = st.button("🎁 ギフトを作る", type="primary")

    if generate_btn:
        with st.spinner("シェフがレシピを考案中..."):
            # AI生成
            recipe_data = generate_recipe_json(ingredients, mode, condition, target, user_message)
            
            # --- Web画面表示エリア ---
            st.markdown("---")
            col1, col2 = st.columns([2, 1])
            
            with col1:
                st.header(recipe_data['title'])
                st.caption(f"For: {target} | ⏱ {recipe_data['cooking_time']}")
                
                if user_message:
                    st.info(f"{user_message}")

                st.subheader("🛒 材料")
                # 材料をMarkdownの表形式で表示
                md_table = "| 食材 | 分量 |\n|---|---|\n"
                for item in recipe_data['ingredients']:
                    md_table += f"| {item['name']} | {item['amount']} |\n"
                st.markdown(md_table)

            with col2:
                # 作り方を右側に（スマホだと下に来ます）
                st.subheader("🍳 作り方")
                for i, step in enumerate(recipe_data['steps'], 1):
                    st.write(f"**{i}.** {step}")
            
            # --- PDF生成 & ダウンロード ---
            st.markdown("---")
            st.subheader("🎁 完成したギフト")
            pdf_bytes = create_pdf_bytes(recipe_data, target, user_message)
            
            if pdf_bytes:
                st.download_button(
                    label="📄 ギフトPDFをダウンロード",
                    data=pdf_bytes,
                    file_name="recipe_gift.pdf",
                    mime="application/pdf",
                    use_container_width=True # ボタンを横幅いっぱいに
                )

if __name__ == "__main__":
    main()

